/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package example.avro.datatype.test;  
@SuppressWarnings("all")
/** An eating utensil. */
@org.apache.avro.specific.AvroGenerated
public enum Enum { 
  KNIFE, FORK, SPOON  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Enum\",\"namespace\":\"example.avro.datatype.test\",\"doc\":\"An eating utensil.\",\"symbols\":[\"KNIFE\",\"FORK\",\"SPOON\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
